/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
import 'package:flutter/widgets.dart';

class AppIcon {
  AppIcon._();

  static const _kFontFam = 'MyIcons';
  //static const String _kFontPkg = null;

  static const IconData ic_launcher_background =
      IconData(0xe800, fontFamily: _kFontFam);
  static const IconData ic_showmenu = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData ic_trans = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData ic_emoji = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData ic_hidemenu = IconData(0xe804, fontFamily: _kFontFam);
}
